editor_gui:
  editor_title: "§8Настройка магазина"
  #Настройка первого зелёного стекла.
  first_item:
    title: "§2Первый ингредиент" #Название предмета.
    material: LIME_STAINED_GLASS_PANE #ID предмета (если нужно заменить стекло на что-то другое).
    lore: #Описание для предмета
      - ""
      - §6В данный слот нужно расположить
      - §4ПЕРВЫЙ §6ингредиент для обмена
  #Настройка второго зелёного стекла.
  second_item:
    title: "§2Второй ингредиент"
    material: LIME_STAINED_GLASS_PANE
    lore:
      - ""
      - §6В данный слот нужно расположить
      - §4ВТОРОЙ §6ингредиент для обмена
  #Настройка красного стекла.
  result_item:
    title: "§2Результат обмена"
    material: RED_STAINED_GLASS_PANE
    lore:
      - ""
      - §6В данный слот нужно расположить
      - §6результат обмена.
      - ""
      - §cЧтобы рецепт работал, он должен иметь
      - §4МИНИМУМ §cодин ингредиент и результат!
